[build]
publish = "exampleSite/public"
command = "npm install tinacms build && hugo"

[build.environment]
HUGO_VERSION = "0.147.2"
NODE_VERSION = "18"  
GO_VERSION = "1.24.3"
HUGO_BASEURL = "exampleSite"
